name: qctools

on: [push, pull_request]

jobs:
  build-unix:

    strategy:
      matrix:
        compiler: ['gcc-7', 'gcc-8', 'gcc-9', 'clang-6', 'clang-9']
        include:
          - compiler: gcc-7
            packages: gcc-7 g++-7
            env: { 'CC': 'gcc-7', 'CXX': 'g++-7' }
          - compiler: gcc-8
            packages: gcc-8 g++-8
            env: { 'CC': 'gcc-8', 'CXX': 'g++-8' }
          - compiler: gcc-9
            packages: gcc-9 g++-9
            env: { 'CC': 'gcc-9', 'CXX': 'g++-9' }
          - compiler: clang-6
            packages: ''
            env: { 'CC': 'clang-6.0', 'CXX': 'clang++-6.0' }
          - compiler: clang-9
            packages: 'clang-9'
            env: { 'CC': 'clang-9', 'CXX': 'clang++-9' }

    runs-on: ubuntu-latest

    env: ${{ matrix.env }}

    steps:
    - uses: actions/checkout@v2.0.0
      with:
        fetch: 1

    - name: Add Clang apt repository
      if: matrix.compiler == 'clang-9'
      run: |
        echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main" \
        | sudo tee -a /etc/apt/sources.list.d/llvm.list
        curl -L https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt-get update

    - name: Install compiler and FFmpeg dependencies
      run: |
        sudo add-apt-repository ppa:jonathonf/ffmpeg-4
        sudo apt-get update &&
        sudo apt-get install -y ${{ matrix.packages }} \
                                libavcodec-dev \
                                libavformat-dev \
                                libavdevice-dev

    - name: Install Qt 5.12.6
      uses: jurplel/install-qt-action@v2

    - name: Cleanup
      run: |
        sudo apt-get clean -y
        sudo rm -rf /var/lib/apt/lists/*

    - name: Build qwt
      run: |
        git clone --depth 1 https://github.com/opencor/qwt ../qwt
        patch ../qwt/qwtconfig.pri script/qwt.patch
        cd ../qwt
        qmake -r
        make -j4

    - name: Build QCTools
      run: |
        cd Project/QtCreator
        qmake
        make -j4
