name: qctools

on: [push, pull_request]

jobs:
  windows-vs:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2.0.0
      with:
        fetch: 1

    - name: Set vswhere path
      run: |
        $VsPath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer"
        echo "::add-path::$VsPath"

    - name: Set MSVC x86_64 paths
      run: |
        $LinkGlob = "VC\Tools\MSVC\*\bin\Hostx64\x64"
        $LinkPath = vswhere -latest -products * -find "$LinkGlob" |
                    Select-Object -Last 1
        echo "::add-path::$LinkPath"

    - name: Install jom
      run: |
        choco install jom

    - name: Build and install zlib
      shell: cmd
      run: |
        set "VS_PATH=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019"
        call "%VS_PATH%\\Enterprise\\VC\\Auxiliary\\Build\\vcvarsall.bat" x64
        git clone --depth 1 https://github.com/madler/zlib ../zlib-dev
        cd ../zlib-dev
        mkdir build
        cd build
        cmake -G "NMake Makefiles JOM" ^
              -DCMAKE_INSTALL_PREFIX="%GITHUB_WORKSPACE%\..\zlib" ^
              -DBUILD_SHARED_LIBS=1 ^
              -DCMAKE_BUILD_TYPE=Release ^
              ..
        jom -j4 install

    - name: Install Qt 5.12.6
      uses: jurplel/install-qt-action@v2

    - name: Install FFmpeg
      run: |
        cd ..
        $FFMPEG_VERSION = "ffmpeg-4.2.1-win64"
        $LINK_DEV = "https://ffmpeg.zeranoe.com/builds/win64/dev"
        $LINK_SHARED = "https://ffmpeg.zeranoe.com/builds/win64/shared"
        curl -LO "$LINK_DEV/$FFMPEG_VERSION-dev.zip"
        curl -LO "$LINK_SHARED/$FFMPEG_VERSION-shared.zip"
        7z x "$FFMPEG_VERSION-dev.zip"
        7z x "$FFMPEG_VERSION-shared.zip"
        Rename-Item -Path ".\$FFMPEG_VERSION-dev" -NewName ".\ffmpeg"
        Rename-Item -Path ".\$FFMPEG_VERSION-shared" -NewName ".\ffmpeg_shared"
        Move-Item -Path .\ffmpeg\include\* -Destination .\ffmpeg\
        Move-Item -Path .\ffmpeg_shared\bin\* -Destination .\ffmpeg\lib

    - name: Download and configure qwt
      run: |
        git clone --depth 1 https://github.com/opencor/qwt ../qwt
        cd ../qwt
        qmake -r

    - name: Build qwt
      shell: cmd
      run: |
        set "VS_PATH=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019"
        call "%VS_PATH%\\Enterprise\\VC\\Auxiliary\\Build\\vcvarsall.bat" x64
        cd ../qwt
        jom -j4

    - name: Configure QCTools
      run: |
        cd Project/QtCreator
        qmake

    - name: Build QCTools
      shell: cmd
      run: |
        set "VS_PATH=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019"
        call "%VS_PATH%\\Enterprise\\VC\\Auxiliary\\Build\\vcvarsall.bat" x64
        cd Project/QtCreator
        jom -j4
